"use client"

import React from 'react';
// Import 'motion' and the 'Variants' type
import { motion, Variants } from 'framer-motion'; 
import { Target, Bot, MessagesSquare, History } from 'lucide-react';

// Card data - easy to manage and update
const qualityFeatures = [
  {
    icon: <Target className="h-10 w-10 text-blue-500" />,
    title: "High Accuracy",
    description: "Predicts the risk of gallstones with up to 95% accuracy using our advanced AI model."
  },
  {
    icon: <Bot className="h-10 w-10 text-blue-500" />,
    title: "AI-Generated Reports",
    description: "Receive detailed, easy-to-understand health reports generated by our intelligent system."
  },
  {
    icon: <MessagesSquare className="h-10 w-10 text-blue-500" />,
    title: "24/7 AI Assistant",
    description: "Our chatbot is always available to answer any questions you have about gallstones."
  },
  {
    icon: <History className="h-10 w-10 text-blue-500" />,
    title: "Patient History",
    description: "Securely access your past predictions and health records anytime you need them."
  }
];

// Framer Motion animation variants
// Apply the 'Variants' type here
const containerVariants: Variants = { 
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2,
    }
  }
};

// And apply the 'Variants' type here
const cardVariants: Variants = { 
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      type: "spring",
      stiffness: 100,
    }
  }
};

export default function Quality() {
  return (
    <section className="bg-gray-50 py-16 sm:py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 tracking-tight">
            A Proactive Approach to Your Health
          </h2>
          <p className="mt-4 max-w-2xl mx-auto text-lg text-gray-600">
            Our platform provides a suite of powerful, AI-driven tools to keep you informed.
          </p>
        </div>

        {/* Animated Card Grid */}
        <motion.div
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
        >
          {qualityFeatures.map((feature, index) => (
            <motion.div
              key={index}
              className="bg-white p-8 rounded-xl shadow-lg border border-gray-200 flex flex-col items-center text-center"
              variants={cardVariants}
              whileHover={{ 
                scale: 1.05, 
                boxShadow: "0px 15px 30px -10px rgba(0, 0, 0, 0.1)",
                borderColor: "rgb(59 130 246)"
              }}
              transition={{ type: "spring", stiffness: 300 }}
            >
              <div className="bg-blue-100 p-4 rounded-full mb-6">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-600 leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}