import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "./Components/Navbar/page";
import Footer from "./Components/Footer/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Capstone App",
  description: "Generated by Next.js & Convex",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {/* Navbar at the top */}
          <Navbar />

          {/* Main content */}
          <main>{children}</main>

          {/* Footer at the bottom */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
